# Generated by Django 5.2.3 on 2025-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('authors', models.CharField(max_length=255, verbose_name='authors')),
                ('average_rating', models.FloatField(verbose_name='average rating')),
                ('num_pages', models.IntegerField(verbose_name='number of pages')),
                ('ratings_count', models.IntegerField(verbose_name='rating count')),
                ('text_review_count', models.IntegerField(verbose_name='text review count')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='publication date')),
                ('publisher', models.CharField(max_length=150, verbose_name='publisher')),
            ],
        ),
    ]
