# Generated by Django 5.2.3 on 2025-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('gender', models.CharField(max_length=12, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('category', models.CharField(max_length=30, verbose_name='Product Category')),
                ('price', models.IntegerField(verbose_name='Price per Unit')),
                ('total', models.IntegerField(verbose_name='Total Amount')),
            ],
        ),
    ]
